chore: merge next into main for production release (#55)
Co-authored-by: TWIN GitHub Bot <github@twindev.org>

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -3,6 +3,17 @@ name: Build
 on:
   workflow_dispatch:
   pull_request:
+    branches:
+      - next
+    paths-ignore:
+      - '**/*.md'
+      - '.github/**'
+  push:
+    branches:
+      - next
+    paths-ignore:
+      - '**/*.md'
+      - '.github/**'
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
@@ -10,41 +21,58 @@ concurrency:
 
 jobs:
   dist-all-packages:
-    runs-on: ubuntu-latest
-
-    # Add env vars for tests
-    env:
-      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
-      TEST_2_MNEMONIC: ${{ secrets.TEST_2_MNEMONIC }}
-      TEST_NODE_MNEMONIC: ${{ secrets.TEST_NODE_MNEMONIC }}
-      TEST_GAS_STATION_ENDPOINT: ${{ vars.TEST_GAS_STATION_ENDPOINT || 'http://localhost:9527' }}
-      TEST_GAS_STATION_AUTH_TOKEN: ${{ secrets.TEST_GAS_STATION_AUTH_TOKEN }}
+    # No need to trigger on merging pull request 'chore: release next'
+    # or 'docs: regenerate package documentation' as they have already performed a build
+    if: "${{ github.event_name != 'push' || (!startsWith(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'chore: release next') && !startsWith(github.event.head_commit.message, 'docs: regenerate package documentation') && !startsWith(github.event.head_commit.message, 'chore: merge next into main for production release')) }}"
+    runs-on:
+      labels: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}
+      group: ${{ github.event.repository.private && 'twin' || 'default' }}
 
     steps:
-      # Get the code
+      # Clone the repository to the runner
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
+
+      # Load test environment variables into the runner environment
+      - name: Load Test Environment Variables
+        shell: bash
+        run: |
+          printf '%s\n' "${{ secrets.TWIN_TEST_ENV_VARS }}" >> "$GITHUB_ENV"
 
       # Setup Node
       - name: Setup Node
-        uses: actions/setup-node@v4
+        uses: actions/setup-node@v6
         with:
-          node-version: 20
+          node-version: 24
 
-      # Install dependencies
+      # Install dependencies with retry
       - name: Install dependencies
-        run: npm ci
+        run: |
+          for i in {1..5}; do
+            npm ci && break || {
+              if [ $i -eq 5 ]; then
+                echo "npm ci failed after 3 attempts"
+                exit 1
+              fi
+              echo "npm ci failed, retrying in 30 seconds (attempt $i/3)..."
+              sleep 30
+            }
+          done
 
-      # Setup test environment
-      - name: Setup test environment
-        uses: ./.github/actions/setup-test-environment
+      # Setup any services required for tests here
+      - name: Setup Test Environment
+        uses: ./.github/workflows/setup-test-env
         with:
-          test-node-endpoint: ${{ vars.TEST_NODE_ENDPOINT || 'https://api.testnet.iota.cafe' }}
-          test-faucet-endpoint: ${{ vars.TEST_FAUCET_ENDPOINT || 'https://faucet.testnet.iota.cafe/gas' }}
-          gas-station-auth: 'qEyCL6d9BKKFl/tfDGAKeGFkhUlf7FkqiGV7Xw4JUsI='
+          test_env_vars: ${{ secrets.TWIN_TEST_ENV_VARS }}
 
       # Run Lint and Dist
       - name: Run Lint and Dist
         run: |
           npm run lint
           npm run dist
+          npm run docs
+
+      # Always teardown the environment, necessary to cleanup self-hosted
+      - name: Teardown Test Environment
+        if: always()
+        uses: ./.github/workflows/teardown-test-env
